### ISSUE TITLE
should save the game path to .config/asma

### ISSUE THREAD

**Issue by Preisschild** [busquetsaguilopau/asma#11]
would be nice, that we dont need to set it every restart new.

**Comment by her001** [comment]
To add a bit to this, it really should use `$XDG_CONFIG_HOME`, then use `~/.config` if that isn't found. 

On the other hand, it may be preferable to use [gconf](https://projects.gnome.org/gconf). I would prefer having a config file, but I haven't really weighed the benefits of each.

**Comment by her001** [comment]
I chose to use the dconf backend of GSettings, so it is stored there instead of a config file in ~/.config/asma.
